# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  ignore: # we neeed to ignore these updates while we still support API 16
    - dependency-name: "com.squareup.okhttp3:okhttp"
      versions: ">= 3.13"
    - dependency-name: "com.squareup.okhttp3:mockwebserver"
      versions: ">= 3.13"
    - dependency-name: "com.mikepenz:iconics-core"
      versions: ">= 5"
    - dependency-name: "com.mikepenz:iconics-views"
      versions: ">= 5"
    - dependency-name: 'com.github.zawadz88.materialpopupmenu:material-popup-menu'
      versions: ">= 3.5"
    - dependency-name: 'com.squareup.picasso:picasso'
      versions: "2.71828"
    - dependency-name: 'jp.wasabeef:picasso-transformations'
      versions: ">= 2.4"

